blank_issues_enabled: true
contact_links:
  - name: Questions / Discussions
    url: https://github.com/MariaMoradzadeh/weather-etl/discussions
    about: Ask questions or start a discussion (enable Discussions if needed).
